# Generated by Django 4.2.13 on 2024-06-18 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_DH', models.CharField(max_length=255)),
                ('hen_giao', models.DateTimeField(blank=True, null=True)),
                ('nguon', models.CharField(blank=True, max_length=255, null=True)),
                ('phuong_thuc_thanh_toan', models.CharField(blank=True, max_length=255, null=True)),
                ('tham_chieu', models.CharField(blank=True, max_length=255, null=True)),
                ('duong_dan_don_hang', models.CharField(blank=True, max_length=255, null=True)),
                ('tong_DH', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_loai_SP', models.CharField(max_length=255)),
                ('ten_loai_SP', models.CharField(blank=True, max_length=255, null=True)),
                ('ghi_chu_SP', models.CharField(blank=True, max_length=10000, null=True)),
                ('ngay_tao_loai_SP', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NhanHieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nhan_hieu', models.CharField(max_length=255)),
                ('ten_nhan_hieu', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NhomKhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nhom_KH', models.CharField(max_length=255)),
                ('ten_nhom_KH', models.CharField(blank=True, max_length=255, null=True)),
                ('loai_nhom_KH', models.CharField(blank=True, max_length=255, null=True)),
                ('mo_ta_nhom_KH', models.CharField(blank=True, max_length=10000, null=True)),
                ('so_luong_KH', models.IntegerField(blank=True, null=True)),
                ('ngay_tao_nhom_KH', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NhomNhaCungCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nhom_NCC', models.CharField(max_length=255)),
                ('ten_nhom_NCC', models.CharField(blank=True, max_length=255, null=True)),
                ('ghi_chu_NCC', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_SP', models.CharField(max_length=255)),
                ('ten_SP', models.CharField(blank=True, max_length=255, null=True)),
                ('khoi_luong_SP', models.CharField(blank=True, max_length=255, null=True)),
                ('ma_vach_SP', models.CharField(blank=True, max_length=255, null=True)),
                ('don_vi_tinh_SP', models.CharField(blank=True, max_length=255, null=True)),
                ('gia_ban_le_SP', models.IntegerField(blank=True, null=True)),
                ('gia_ban_buon_SP', models.IntegerField(blank=True, null=True)),
                ('gia_nhap_SP', models.IntegerField(blank=True, null=True)),
                ('anh_SP', models.ImageField(blank=True, null=True, upload_to='')),
                ('gia_von', models.IntegerField(blank=True, null=True)),
                ('ton_kho_ban_dau', models.IntegerField(blank=True, null=True)),
                ('loai_SP_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pos.loaisanpham')),
                ('nhan_hieu_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pos.nhanhieu')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(blank=True, null=True)),
                ('don_gia', models.IntegerField(blank=True, null=True)),
                ('chiet_khau', models.FloatField(blank=True, null=True)),
                ('thanh_tien', models.IntegerField(blank=True, null=True)),
                ('DH_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pos.donhang')),
                ('SP_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pos.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_NCC', models.CharField(max_length=255)),
                ('ten_NCC', models.CharField(blank=True, max_length=255, null=True)),
                ('so_dien_thoai_NCC', models.CharField(blank=True, max_length=255, null=True)),
                ('email_NCC', models.EmailField(blank=True, max_length=255, null=True)),
                ('khu_vuc_NCC', models.CharField(blank=True, max_length=10000, null=True)),
                ('phuong_xa_NCC', models.CharField(blank=True, max_length=10000, null=True)),
                ('dia_chi_1_NCC', models.CharField(blank=True, max_length=10000, null=True)),
                ('dia_chi_2_NCC', models.CharField(blank=True, max_length=10000, null=True)),
                ('so_fax_NCC', models.CharField(blank=True, max_length=255, null=True)),
                ('ma_so_thue_NCC', models.CharField(blank=True, max_length=255, null=True)),
                ('website_NCC', models.CharField(blank=True, max_length=255, null=True)),
                ('cong_no_NCC', models.IntegerField(blank=True, null=True)),
                ('nhom_NCC_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pos.nhomnhacungcap')),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_KH', models.CharField(max_length=255)),
                ('ten_KH', models.CharField(blank=True, max_length=255, null=True)),
                ('so_dien_thoai_KH', models.CharField(blank=True, max_length=255, null=True)),
                ('email_KH', models.EmailField(blank=True, max_length=255, null=True)),
                ('khu_vuc_KH', models.CharField(blank=True, max_length=10000, null=True)),
                ('phuong_xa_KH', models.CharField(blank=True, max_length=10000, null=True)),
                ('dia_chi_cu_the_KH', models.CharField(blank=True, max_length=10000, null=True)),
                ('ngay_sinh_KH', models.DateField(blank=True, null=True)),
                ('gioi_tinh_KH', models.CharField(blank=True, max_length=255, null=True)),
                ('so_fax_KH', models.CharField(blank=True, max_length=255, null=True)),
                ('ma_so_thue_KH', models.CharField(blank=True, max_length=255, null=True)),
                ('website_KH', models.CharField(blank=True, max_length=255, null=True)),
                ('cong_no_KH', models.IntegerField(blank=True, null=True)),
                ('tong_chi_tieu_KH', models.IntegerField(blank=True, null=True)),
                ('nhom_KH_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pos.nhomkhachhang')),
            ],
        ),
        migrations.AddField(
            model_name='donhang',
            name='KH_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pos.khachhang'),
        ),
    ]
