# Generated by Django 4.2.13 on 2024-06-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderLine',
            new_name='TungDonHang',
        ),
    ]
