# Generated by Django 4.2.13 on 2024-06-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_rename_orderline_tungdonhang'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TungDonHang',
            new_name='STTDonHang',
        ),
    ]
