# Generated by Django 4.2.13 on 2024-06-18 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_rename_tungdonhang_sttdonhang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_code', models.CharField(max_length=255)),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=255)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=10000, null=True)),
                ('ward', models.CharField(blank=True, max_length=10000, null=True)),
                ('specific_address', models.CharField(blank=True, max_length=10000, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('fax_number', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_code', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('debt', models.IntegerField(blank=True, null=True)),
                ('total_spending', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(max_length=255)),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('group_type', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('customer_count', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=255)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('order_link', models.CharField(blank=True, max_length=255, null=True)),
                ('total_amount', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pos.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.IntegerField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pos.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=255)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_of_measurement', models.CharField(blank=True, max_length=255, null=True)),
                ('retail_price', models.IntegerField(blank=True, null=True)),
                ('wholesale_price', models.IntegerField(blank=True, null=True)),
                ('purchase_price', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('cost_price', models.IntegerField(blank=True, null=True)),
                ('initial_stock', models.IntegerField(blank=True, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pos.brand')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=255)),
                ('type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=10000, null=True)),
                ('creation_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(max_length=255)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=10000, null=True)),
                ('ward', models.CharField(blank=True, max_length=10000, null=True)),
                ('address_1', models.CharField(blank=True, max_length=10000, null=True)),
                ('address_2', models.CharField(blank=True, max_length=10000, null=True)),
                ('fax_number', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_code', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('debt', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(max_length=255)),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='khachhang',
            name='nhom_KH_obj',
        ),
        migrations.RemoveField(
            model_name='nhacungcap',
            name='nhom_NCC_obj',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='loai_SP_obj',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='nhan_hieu_obj',
        ),
        migrations.RemoveField(
            model_name='sttdonhang',
            name='DH_obj',
        ),
        migrations.RemoveField(
            model_name='sttdonhang',
            name='SP_obj',
        ),
        migrations.DeleteModel(
            name='DonHang',
        ),
        migrations.DeleteModel(
            name='KhachHang',
        ),
        migrations.DeleteModel(
            name='LoaiSanPham',
        ),
        migrations.DeleteModel(
            name='NhaCungCap',
        ),
        migrations.DeleteModel(
            name='NhanHieu',
        ),
        migrations.DeleteModel(
            name='NhomKhachHang',
        ),
        migrations.DeleteModel(
            name='NhomNhaCungCap',
        ),
        migrations.DeleteModel(
            name='SanPham',
        ),
        migrations.DeleteModel(
            name='STTDonHang',
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pos.suppliergroup'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pos.producttype'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pos.product'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pos.customergroup'),
        ),
    ]
