# Generated by Django 4.2.13 on 2024-06-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_brand_customer_customergroup_order_orderline_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
