# Generated by Django 4.2.13 on 2024-06-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_order_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
