# Generated by Django 4.2.13 on 2024-06-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_alter_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
