# Generated by Django 4.2.13 on 2024-06-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_alter_orderline_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
