# Generated by Django 4.2.13 on 2024-06-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_alter_product_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='order_line_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
